---

- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open http service in firewall
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Open https service in firewall
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
    offline: true
