---
- name: Configure all managed nodes with baseline
  hosts: webservers:dbservers
  become: true
  roles:
    - repo_client
    - base_config
    - user_mgmt
    - storage_config

- name: Configure web servers
  hosts: webservers
  become: true
  roles:
    - web_server
    - firewall_config

- name: Configure database servers
  hosts: dbservers
  become: true
  roles:
    - db_config
